# Generated by Django 5.2 on 2025-04-03 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('tf', models.FloatField(help_text='Term Frequency')),
                ('idf', models.FloatField(blank=True, help_text='Inverse Document Frequency', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_stats', to='document.document')),
            ],
            options={
                'indexes': [models.Index(fields=['word'], name='document_wo_word_3bd16d_idx'), models.Index(fields=['idf'], name='document_wo_idf_90d463_idx')],
            },
        ),
    ]
